tableName: "players"
chatActivityRatio: 0.5
gameActivityRatio: 0.5
db:
  host: "localhost"
  port: "3307"
  dbName: "rank-system"
  login: "rankSystemPlugin"
  password: "12345678"

discordAnnoyMessage:
- |-
You haven't linked a discord
If you link a discord, we will be able to give you a rank on our discord server
discordLinkMessage:
  - |-
    To bind the discord, [copy] the id and write to our bot /minecraft <your-id>
    The bot is located on our discord server https://discord .gg/sKgypSe7gW
